train:
  _target_: src.datasets.LibrispeechDataset
  part: test-clean
  data_dir: /workspace/data
  target_sr: 16000
  limit: 16
  shuffle_index: True
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LibrispeechDataset
  part: test-clean
  data_dir: /workspace/data
  target_sr: 16000
  limit: 8
  instance_transforms: ${transforms.instance_transforms.inference}
