train:
  _target_: src.datasets.LibrispeechDataset
  part: train-clean-100
  data_dir: /workspace/data
  target_sr: 16000
  shuffle_index: True
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LibrispeechDataset
  part: test-clean
  data_dir: /workspace/data
  target_sr: 16000
  sort_by_length: True
  max_audio_length: 30.0
  limit: 200
  instance_transforms: ${transforms.instance_transforms.inference}
