_target_: src.logger.WandBWriter
project_name: "hw04-soundstream"
entity: null
run_name: "v2-no-normalize-amp-kmeans50-alphafix"
mode: "online"
loss_names: ["loss", "loss_recon", "loss_adv", "loss_fm", "loss_commit", "loss_d"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
